"""Documentation Pipeline - Generate docs from codebases.

Chains multiple MCP tools:
1. Ollama Enhancement - Refine the documentation request
2. Sequential Thinking - Structure content logically
3. Desktop Commander - Write to Obsidian vault

Usage:
    POST /pipelines/documentation
    {
        "repo_path": "/path/to/repo",
        "project_name": "my-project",
        "vault_path": "~/Obsidian/Projects"
    }
"""

import logging
from datetime import datetime
from pathlib import Path
from typing import Any

from router.models import JSONRPCRequest

logger = logging.getLogger(__name__)


async def documentation_pipeline(
    repo_path: str,
    project_name: str,
    vault_path: str = "~/Obsidian/Projects",
    enhance_fn: Any = None,
    route_fn: Any = None,
) -> dict[str, Any]:
    """Generate documentation from a codebase and write to Obsidian.

    Args:
        repo_path: Path to the repository to document
        project_name: Name for the output file
        vault_path: Path to Obsidian vault (default: ~/Obsidian/Projects)
        enhance_fn: Enhancement function (injected from main)
        route_fn: Server routing function (injected from main)

    Returns:
        Dictionary with status, output_path, and obsidian_url
    """
    logger.info(f"Starting documentation pipeline for {project_name}")

    # Expand vault path
    expanded_vault = str(Path(vault_path).expanduser())
    output_path = f"{expanded_vault}/{project_name}.md"

    # Step 1: Create documentation prompt
    doc_prompt = f"""
Generate comprehensive technical documentation for the project at: {repo_path}

Include the following sections:
1. **Overview** - What the project does, its purpose
2. **Architecture** - Key components and how they interact
3. **Setup Instructions** - How to install and run
4. **Key Components** - Main modules/files and their responsibilities
5. **Common Workflows** - Typical usage patterns
6. **Configuration** - Available options and environment variables

Format the output in Markdown with clear headers.
Use code blocks for commands and examples.
Keep explanations concise but complete.
"""

    # Step 2: Enhance the prompt via Ollama
    enhanced_content = doc_prompt
    if enhance_fn:
        try:
            result = await enhance_fn(
                prompt=doc_prompt,
                client="documentation-pipeline",
            )
            enhanced_content = result.get("enhanced", doc_prompt)
            logger.info("Documentation prompt enhanced via Ollama")
        except Exception as e:
            logger.warning(f"Enhancement failed, using original prompt: {e}")

    # Step 3: Structure with Sequential Thinking (if available)
    structured_content = enhanced_content
    if route_fn:
        try:
            think_request = JSONRPCRequest(
                method="tools/call",
                params={
                    "name": "sequentialthinking",
                    "arguments": {
                        "thought": enhanced_content,
                        "thought_number": 1,
                        "total_thoughts": 3,
                    },
                },
            )
            response = await route_fn("sequential-thinking", think_request)
            if response.result:
                structured_content = str(response.result)
                logger.info("Content structured via Sequential Thinking")
        except Exception as e:
            logger.warning(f"Sequential thinking failed: {e}")

    # Step 4: Generate final document
    timestamp = datetime.now().isoformat()
    doc_content = f"""---
tags: [project, documentation, auto-generated]
created: {timestamp}
source: {repo_path}
generator: mcp-router
---

# {project_name}

{structured_content}

---

*Generated by MCP Router Documentation Pipeline*
*Source: {repo_path}*
*Generated: {timestamp}*
"""

    # Step 5: Write to file (via Desktop Commander if available, else direct)
    write_success = False
    if route_fn:
        try:
            write_request = JSONRPCRequest(
                method="tools/call",
                params={
                    "name": "write_file",
                    "arguments": {
                        "path": output_path,
                        "content": doc_content,
                    },
                },
            )
            response = await route_fn("desktop-commander", write_request)
            if not response.error:
                write_success = True
                logger.info(f"Documentation written via Desktop Commander: {output_path}")
        except Exception as e:
            logger.warning(f"Desktop Commander write failed: {e}")

    # Fallback: Direct file write
    if not write_success:
        try:
            output_file = Path(output_path).expanduser()
            output_file.parent.mkdir(parents=True, exist_ok=True)
            output_file.write_text(doc_content)
            write_success = True
            logger.info(f"Documentation written directly: {output_path}")
        except Exception as e:
            logger.error(f"Failed to write documentation: {e}")
            return {
                "status": "error",
                "error": str(e),
                "content_preview": doc_content[:500],
            }

    # Generate Obsidian URL
    vault_name = Path(expanded_vault).parent.name
    obsidian_url = f"obsidian://open?vault={vault_name}&file=Projects/{project_name}"

    return {
        "status": "complete",
        "output_path": output_path,
        "obsidian_url": obsidian_url,
        "sections": [
            "Overview",
            "Architecture",
            "Setup Instructions",
            "Key Components",
            "Common Workflows",
            "Configuration",
        ],
    }
