#!/bin/bash
# Generate .env file from Keychain secrets using ks
# Usage: ./scripts/gen-env-from-ks.sh [output_file]

set -euo pipefail

OUTPUT_FILE="${1:-.env}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

echo "Generating $OUTPUT_FILE from Keychain secrets..."

# Start with the example file as base
if [[ -f "$PROJECT_ROOT/.env.example" ]]; then
    cp "$PROJECT_ROOT/.env.example" "$OUTPUT_FILE"
else
    echo "Warning: .env.example not found, creating minimal .env"
    cat > "$OUTPUT_FILE" << 'EOF'
# Generated by gen-env-from-ks.sh
OLLAMA_HOST=host.docker.internal
OLLAMA_PORT=11434
OLLAMA_MODEL=deepseek-r1
ROUTER_HOST=0.0.0.0
ROUTER_PORT=9090
LOG_LEVEL=info
EOF
fi

# Map of env var names to ks secret keys
declare -A SECRET_MAP=(
    ["OBSIDIAN_API_KEY"]="obsidian_api_key"
    ["FIGMA_API_KEY"]="figma_api_key"
    ["GITHUB_TOKEN"]="github_token"
)

# Append secrets from Keychain
echo "" >> "$OUTPUT_FILE"
echo "# Secrets loaded from Keychain ($(date +%Y-%m-%d))" >> "$OUTPUT_FILE"

for env_var in "${!SECRET_MAP[@]}"; do
    ks_key="${SECRET_MAP[$env_var]}"
    
    # Try to get secret from ks (suppress errors for missing keys)
    if secret=$(ks show "$ks_key" 2>/dev/null); then
        echo "${env_var}=${secret}" >> "$OUTPUT_FILE"
        echo "  ✓ Loaded $env_var from ks:$ks_key"
    else
        echo "  - Skipped $env_var (not found in Keychain)"
    fi
done

echo ""
echo "Generated: $OUTPUT_FILE"
echo "Note: Add this file to .gitignore (already configured)"
